/* jCarouflex minified - version: 1.0 (2011) - author: Remy Elazare - http://remylab.net46.net/demos/jquery-plugins/jcarouflex/ */
(function(a){function j(b,i){return parseInt(a.css(b[0],i))||0}a.fn.jCarouflexLite=function(b){b=a.extend({dir:1,btnPrev:null,btnNext:null,speed:800,easing:null,vertical:!1,visible:3,scroll:1,start:1,beforeStart:null,afterEnd:null},b||{});return this.each(function(){function i(e){if(!c){c=!0;b.beforeStart&&b.beforeStart.call(this,f.slice(l,l+1));var h=1==e?a("li",d).slice(2*g,k+2*g).clone():a("li",d).slice(0,k).clone(),e=1==e?-2*g*m:0;d.animate("left"==o?{left:e}:{top:e},b.speed,b.easing,function(){d.empty().append(h).prepend(h.slice(k-
g).clone()).append(h.slice(0,g).clone());d.css(o,-g*m);f=a("li",d);b.afterEnd&&b.afterEnd.call(this,f.slice(l,l+1));c=!1})}return!1}var c=!1,o=b.vertical?"top":"left",p=b.vertical?"height":"width",n=a(this),d=a("ul",n),e=a("li",d),k=e.size(),l=b.visible,g=b.scroll,h=b.start,g=Math.min(b.visible,g),g=Math.max(1,g),h=Math.min(k,h),h=Math.max(1,h);d.empty();e.each(function(){1==b.dir?d.append(this):d.prepend(this)});e=a("li",d);1<h&&(d.append(e.clone()),e=a("li",d).slice(h-1,h+k-1).clone(),d.empty().append(e),
e=a("li",d));d.prepend(e.slice(k-g).clone()).append(e.slice(0,g).clone());var f=a("li",d),e=f.size();n.css("visibility","visible");f.css({overflow:"hidden"});f.css("float",b.vertical?"none":"left");d.css({margin:"0",padding:"0",position:"relative","list-style-type":"none","z-index":"1"});n.css({overflow:"hidden",position:"relative","z-index":"2",left:"0px"});var m=b.vertical?f[0].offsetHeight+j(f,"marginTop")+j(f,"marginBottom"):f[0].offsetWidth+j(f,"marginLeft")+j(f,"marginRight"),e=m*e,h=m*l;f.css({width:f.width(),
height:f.height()});d.css(p,e+"px").css(o,-(g*m));n.css(p,h+"px");a(this).bind("moveDir",function(a,c){return i(c*b.dir)});b.btnPrev&&a(b.btnPrev).click(function(){return i(-1*b.dir)});b.btnNext&&a(b.btnNext).click(function(){return i(1*b.dir)})})}})(jQuery);
jQuery.jCarouflex=function(a){function j(b){$(a.teaser).data(c).stop=!1;$(a.teaser).data(c).pause=b;a.afterPause&&a.afterPause.call(this,$(a.btnPause),$(a.teaser).data(c).pause)}function b(){$(a.teaser).data(c).isMoving=!1;$(a.teaser).data(c).force=!1}function i(){var b=$(a.teaser).data(c);if(!b.pause&&!b.isMoving&&!b.force&&!b.stop)b.dir=1,$(a.teaser).trigger("moveDir",1),$(a.teaser).data(c,b);setTimeout(function(){i()},a.pauseTime)}var a=$.extend({teaser:null,slides:null,teaserNext:null,teaserPrev:null,
btnPause:null,afterPause:null,speed:500,pauseTime:3E3,visibleTeaser:3,visibleSlides:1,verticalTeaser:!1,verticalSlides:!0,teaserScroll:1,slidesScroll:1,teaserDir:1,slidesDir:1,pause:!1},a||{}),c="jCarouflex";$(a.teaser).find("li").size();$(a.teaser).data(c,{dir:1,force:!1,isMoving:!1,stop:!1,pause:a.pause});$(a.teaser).jCarouflexLite({visible:a.visibleTeaser,vertical:a.verticalTeaser,speed:a.speed,scroll:a.teaserScroll,dir:a.teaserDir,start:1==a.teaserDir?a.teaserScroll+1:$("li",a.teaser).length-
a.visibleTeaser-a.teaserScroll+1,userBeforeStart:a.beforeStart,userAfterEnd:a.afterEnd,beforeStart:function(){$(a.teaser).data(c).isMoving=!0;a.slides&&$(a.slides).trigger("moveDir",$(a.teaser).data(c).dir)},afterEnd:function(){null==a.slides&&b()}});$(a.teaser).bind("pause",function(a,b){j(b)});a.btnPause&&$(a.btnPause).bind("click",function(){j(!$(a.teaser).data(c).pause)});a.slides&&$(a.slides).jCarouflexLite({visible:a.visibleSlides,vertical:a.verticalSlides,speed:a.speed,scroll:a.slidesScroll,
dir:a.slidesDir,start:1==a.slidesDir?1:$("li",a.slides).length-a.slidesScroll+1,afterEnd:function(c){a.afterEnd&&a.afterEnd(c);b()},beforeStart:function(b){a.beforeStart&&a.beforeStart(b)}});a.teaserPrev&&$(a.teaserPrev).click(function(){$(a.teaser).data(c).force=!0;$(a.teaser).data(c).dir=-1;$(a.teaser).trigger("moveDir",-1)});a.teaserNext&&$(a.teaserNext).click(function(){$(a.teaser).data(c).force=!0;$(a.teaser).data(c).dir=1;$(a.teaser).trigger("moveDir",1)});$(a.teaser).hasClass("pause")&&($(a.teaser).mouseenter(function(){$(a.teaser).data(c).stop=
!0}),$(a.teaser).mouseleave(function(){$(a.teaser).data(c).stop=!1}));$(a.slides).hasClass("pause")&&($(a.slides).mouseenter(function(){$(a.teaser).data(c).stop=!0}),$(a.slides).mouseleave(function(){$(a.teaser).data(c).stop=!1}));(function(){setTimeout(function(){i()},a.pauseTime)})()};